# helm-chart/values.yaml
replicaCount: 1

image:
  repository: docker.io/kartikeytiwari/assignment
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 5000

env:
  MONGO_URI: "mongodb+srv://tiwarikartikey777:HrcvSeaGfbKbh1pI@cluster0.6w2iedb.mongodb.net/"

probes:
  readiness:
    path: "/health"
    port: 5000
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: "/health"
    port: 5000
    initialDelaySeconds: 10
    periodSeconds: 20

