apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assignment-backend-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: assignment.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "assignment-backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

